<?php

include_once '../../persistance/dao/dao_purchase/ArticleDAO.php';
include_once '../../persistance/dao/dao_purchase/ArticleGroupDAO.php';
include_once '../../persistance/model/ArticleGroup.php';
include_once '../../persistance/model/Article.php';
include_once '../../persistance/dao/dao_purchase/SupplierDAO.php';
include_once '../../persistance/model/Supplier.php';
include_once '../../persistance/model/Address.php';
include_once '../../persistance/dao/AddressDAO.php';
$db = new ArticleDAO;
$article = $db->getArticle($_SESSION['articleNum']);
$vendorDAO = new SupplierDAO;
$vendor = $vendorDAO->getSupplier($article->getVendor());
$vendorName = utf8_encode($vendor->getName());
$articleGroup = utf8_encode($article->getArticleGroup());
$articleDescription = utf8_encode($article->getArticleDesc());

echo "<table>";
echo "<tr>";
echo "<th>Bezeichnung</th>";
echo "<th>Wert</th>";
echo "</tr>";
echo"<tr>";
echo "<td>Artikelnummer</td>";
echo "<td>".$article->getArticleNumber()."</td>";
echo "</tr>";
echo"<tr>";
echo "<td>Alter Artikelname</td>";
echo "<td>$articleDescription</td>";
echo "</tr>";
echo "<tr>";
echo "<td>Alte Artikelgruppe</td>";
echo "<td>$articleGroup</td>";
echo "</tr>";
echo "<tr>";
echo "<td>Alter Einkaufspreis</td>";
echo "<td>".$article->getBuyingPrice()."</td>";
echo "</tr>";
echo "<tr>";
echo "<td>Alter Verkaufspreis</td>";
echo "<td>".$article->getSellingPrice()."</td>";
echo "</tr>";
echo "<tr>";
echo "<td>Alte Basiseinheit</td>";
echo "<td>".$article->getUnit()."</td>";
echo "</tr>";
echo "<tr>";
echo"<td>Alte Verpackungseinheit</td>";
echo "<td>".$article->getPackingUnit()."</td>";
echo "</tr>";
echo "<tr>";
echo"<td>Alte Verpackungsgröße</td>";
echo "<td>".$article->getPackingSize()."</td>";
echo "</tr>";
echo "<tr>";
echo"<td>Alter Mindestbestand</td>";
echo "<td>".$article->getMinimumLevel()."</td>";
echo "</tr>";
echo "<tr>";
echo"<td>Alter Lieferant</td>";
echo "<td>$vendorName</td>";
echo "</tr>";
echo "<tr>";
echo"<td>Alter Margenaufschlag</td>";
echo "<td>".$article->getSurcharge()."</td>";
echo "</tr>";
echo "</table>";
echo "<br/>";
