<?php

include '../../persistance/dao/dao_purchase/ArticleDAO.php';
$db = new ArticleDAO;
$article = $db->getArticle($_SESSION['articleNum']);
echo "<table>";
echo "<tr>";
echo "<th>Bezeichnung</th>";
echo "<th>Wert</th>";
echo "</tr>";
echo"<tr>";
echo "<td>Alter Artikelname</td>";
echo "<td>".$article->getArticleDesc()."</td>";
echo "</tr>";
echo "<tr>";
echo "<td>Alte Artikelgruppe</td>";
echo "<td>".$article->getArticleGroup()."</td>";
echo "</tr>";
echo "<tr>";
echo "<td>Alter Einkaufspreis</td>";
echo "<td>".$article->getBuyingPrice()."</td>";
echo "</tr>";
echo "<tr>";
echo "<td>Alter Verkaufspreis</td>";
echo "<td>".$article->getSellingPrice()."</td>";
echo "</tr>";
echo "<tr>";
echo "<td>Alte Basiseinheit</td>";
echo "<td>".$article->getUnit()."</td>";
echo "</tr>";
echo "<tr>";
echo"<td>Alte Verpackungseinheit</td>";
echo "<td>".$article->getPackingUnit()."</td>";
echo "</tr>";
echo "<tr>";
echo"<td>Alte Verpackungsgröße</td>";
echo "<td>".$article->getPackingSize()."</td>";
echo "</tr>";
echo "<tr>";
echo"<td>Alter Mindestbestand</td>";
echo "<td>".$article->getMinimumLevel()."</td>";
echo "</tr>";
echo "<tr>";
echo"<td>Alter Lieferant</td>";
echo "<td>".$article->getVendor()."</td>";
echo "</tr>";
echo "<tr>";
echo"<td>Alter Margenaufschlag</td>";
echo "<td>".$article->getSurcharge()."</td>";
echo "</tr>";
echo "</table>";
